version: "3.7"
services:
  server:
    image: labflow/script-runner-example:latest
    build:
      dockerfile: ./Dockerfile.example
      context: ./docker
      args:
        SERVER_VERSION: local+devcontainer
    command: "python3 -m flask run --host=0.0.0.0 --port=5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
      - PROPAGATE_EXCEPTIONS=True
      - "SERVER_NAME=${SERVER_NAME}"
      - "AUTH_PROVIDER=none"
      - "CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379"
      - "CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379"
    ports:
      - 5000:5000
    volumes:
      - ./:/app
  worker:
    image: labflow/script-runner-example:latest
    build:
      dockerfile: ./Dockerfile.example
      context: ./docker
      args:
        SERVER_VERSION: local+devcontainer
    command: "python3 -m celery -A script_runner.analysis worker"
    environment:
      - "CELERY_BROKER_URL=redis://:${REDIS_PASSWORD}@redis:6379"
      - "CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD}@redis:6379"
      - "COMMAND_RUNDIR_BASE=/base-rundir"
    volumes:
      - ./:/app
  redis:
    image: redis:6-alpine
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - 6379:6379
